<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/10/19 15:35:52

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'jobeet',
  'password' => 'TXuShj',
  'name' => 'doctrine',
)),);
