<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/10/19 02:18:43

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'jobeet',
  'password' => 'TXuShj',
  'name' => 'doctrine',
)),);
